### ISSUE TITLE
New version of texer container

### ISSUE THREAD

**Issue by clyde-johnston** [OpenCyphal/docker_toolchains#9]
Per @pavel-kirienko in PR [#85](https://github.com/UAVCAN/specification/pull/85) of UAVCAN/specification:
>I think we should also release a new version of the texer container...

Powershell is not yet supported on the latest version of Ubuntu (20.04). We could upgrade to Ubuntu 18.04LTS or the interim 19.04 release. Or, we can drop Powershell from the container and get the latest version of texlive-full.

**Comment by pavel-kirienko** [comment]
Would it not be easier to install the latest TexLive on the existing image? If not, do we have an ETA on PowerShell for Ubuntu 20.04?

**Comment by clyde-johnston** [comment]
The latest TeXLive package is not available on Ubuntu 16.04.

According to Microsoft, PowerShell is not supported on Ubuntu 20.04 (see [here](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#ubuntu-2004)) although some users report success with installing old packages manually on the new OS.  There is [a project](https://github.com/PowerShell/PowerShell/issues/12626) in the works on GitHub to port PowerShell for Ubuntu 20.04 but no ETA yet.

If it is just a new version of TeXLive that you want, I would suggest upgrading the texer container to Ubuntu 18.04 and installing the standard packages on it.  When PowerShell becomes available for Ubuntu 20.04, it should not be a big task to upgrade again.

**Comment by pavel-kirienko** [comment]
Okay, let's do as you suggest. FYI @thirtytwobits

**Comment by pavel-kirienko** [comment]
Seeing as that PR is still not merged, maybe we can take a shortcut and update it to 20.04 while we're at it?

**Comment by pavel-kirienko** [comment]
Never mind. I suppose 18.04 is sufficiently recent so I'm closing it.

**Comment by pavel-kirienko** [comment]
You should know that I tested the build using the most recent `texlive-full` from 20.04 and it builds correctly.
